### ISSUE TITLE
Dependency packages `packages.txt` missing

### ISSUE THREAD

**Issue by soumendrak** [swateek/Quora-Activity-Report#1]
As mentioned in README.MD, packages.txt is missing in the repository.

**Comment by praddyinstant** [comment]
i think the below needs to be there.
selenium
matplotlib

You can just pip install these libraries to test out the report. Additionally we need to download https://github.com/mozilla/geckodriver/releases, untar it and place the directory in your PATH environment variable.

**Comment by swateek** [comment]
Also, I have added it now.
